'use client'

// Content is server-generated by mammoth from admin-uploaded .docx/.pdf only — trusted source
export function JobContent({ html }: { html: string }) {
  return (
    <>
      <div
        className="bg-white border border-[#E2DDD6] px-8 md:px-12 py-10 md:py-14 job-content mb-12"
        ref={(el: HTMLDivElement | null) => { if (el) el.innerHTML = html }}
      />
      <style>{`
        .job-content h1 { font-size:1.5rem;font-weight:700;color:#0e1a7a;margin:1.5rem 0 .75rem;font-family:var(--font-heading);line-height:1.2 }
        .job-content h2 { font-size:1.2rem;font-weight:700;color:#0e1a7a;margin:1.5rem 0 .5rem;font-family:var(--font-heading) }
        .job-content h3 { font-size:1rem;font-weight:600;color:#0e1a7a;margin:1.25rem 0 .4rem }
        .job-content p { color:#374151;font-size:.9375rem;line-height:1.75;margin-bottom:1rem }
        .job-content ul,.job-content ol { color:#374151;font-size:.9375rem;line-height:1.75;margin:.75rem 0 1rem 1.5rem }
        .job-content li { margin-bottom:.35rem }
        .job-content strong { color:#0e1a7a;font-weight:600 }
        .job-content em { color:#64748B }
        .job-content a { color:#0e1a7a;text-decoration:underline }
        .job-content hr { border:none;border-top:1px solid #E2DDD6;margin:2rem 0 }
        .job-content iframe { width:100%;min-height:80vh;border:none }
      `}</style>
    </>
  )
}
