const PRIMARY_DECKS: Record<number, string> = {
  1: '/decks/primary/Week-01-Who-Was-Maria-Montessori.html',
  2: '/decks/primary/Week-02-The-Absorbent-Mind-in-Real-Life.html',
  3: '/decks/primary/Week-03-Practical-Life.html',
  4: '/decks/primary/Week-04-Prepared-Environment-as-Justice.html',
  5: '/decks/primary/Week-05-Care-of-Environment.html',
  6: '/decks/primary/Week-06-Grace-and-Courtesy-Anti-Bias.html',
  7: '/decks/primary/Week-07-Cultural-Dimensions-of-Practical-Life.html',
  8: '/decks/primary/Week-08-Fading-as-a-Practice.html',
  9: '/decks/primary/Week-09-Ready-to-Move-On.html',
  10: '/decks/primary/Week-10-Sensorial-in-the-Brain.html',
  11: '/decks/primary/Week-11-The-Mathematical-Mind.html',
  12: '/decks/primary/Week-12-Normalization.html',
  13: '/decks/primary/Week-13-Sensory-Processing.html',
  14: '/decks/primary/Week-14-The-Three-Period-Lesson.html',
  15: '/decks/primary/Week-15-Control-of-Error.html',
  16: '/decks/primary/Week-16-Adapting-Sensorial.html',
  17: '/decks/primary/Week-17-Science-of-Reading.html',
  18: '/decks/primary/Week-18-Phonological-Awareness.html',
  19: '/decks/primary/Week-19-Dual-Language-Learners.html',
  20: '/decks/primary/Week-20-Moveable-Alphabet.html',
  21: '/decks/primary/Week-21-Decodable-Texts.html',
  22: '/decks/primary/Week-22-Structured-Literacy.html',
  23: '/decks/primary/Week-23-Decimal-System.html',
  24: '/decks/primary/Week-24-Four-Operations.html',
  25: '/decks/primary/Week-25-Passage-to-Abstraction.html',
  26: '/decks/primary/Week-26-Stamp-Game.html',
  27: '/decks/primary/Week-27-Memorization-Work.html',
  28: '/decks/primary/Week-28-Fractions.html',
  29: '/decks/primary/Week-29-Geometry.html',
  30: '/decks/primary/Week-30-Time.html',
  31: '/decks/primary/Week-31-First-Great-Lesson.html',
  32: '/decks/primary/Week-32-Geography.html',
  33: '/decks/primary/Week-33-Botany.html',
  34: '/decks/primary/Week-34-Zoology.html',
  35: '/decks/primary/Week-35-History.html',
  36: '/decks/primary/Week-36-Music.html',
  37: '/decks/primary/Week-37-Art.html',
  38: '/decks/primary/Week-38-Observation.html',
  39: '/decks/primary/Week-39-Families.html',
  40: '/decks/primary/Week-40-Transition-to-Elementary.html',
}

const ELEMENTARY_DECKS: Record<number, string> = {
  1: '/decks/elementary/Week-01-Second-Plane-Child.html',
  2: '/decks/elementary/Week-02-Cosmic-Education.html',
  3: '/decks/elementary/Week-03-Great-Lessons-as-Equity.html',
  4: '/decks/elementary/Week-04-Role-of-the-Guide.html',
  5: '/decks/elementary/Week-05-Imagination-as-Cognitive-Tool.html',
  6: '/decks/elementary/Week-06-Geography-as-Justice.html',
  7: '/decks/elementary/Week-07-Fundamental-Needs-Framework.html',
  8: '/decks/elementary/Week-08-Going-Out.html',
  9: '/decks/elementary/Week-09-Prepared-Elementary-Environment.html',
  10: '/decks/elementary/Week-10-Biology-and-Cosmic-Education.html',
  11: '/decks/elementary/Week-11-Classification-as-Thinking-Tool.html',
  12: '/decks/elementary/Week-12-Supporting-Neurodivergent-Children.html',
  13: '/decks/elementary/Week-13-Human-Body-and-Body-Autonomy.html',
  14: '/decks/elementary/Week-14-Evolution-and-the-Elementary-Classroom.html',
  15: '/decks/elementary/Week-15-Ecology-Interdependence-and-Environmental-Justice.html',
  16: '/decks/elementary/Week-16-Botany-and-Zoology-as-Research-Foundations.html',
  17: '/decks/elementary/Week-17-History-and-the-Third-Great-Lesson.html',
  18: '/decks/elementary/Week-18-Ancient-Civilizations-Whose-Get-Ancient-Status.html',
  19: '/decks/elementary/Week-19-Passage-of-Time-and-Historical-Consciousness.html',
  20: '/decks/elementary/Week-20-Trauma-Informed-History-Teaching.html',
  21: '/decks/elementary/Week-21-The-Midpoint.html',
  22: '/decks/elementary/Week-22-Mathematics-at-the-Second-Plane.html',
  23: '/decks/elementary/Week-23-Geometry-as-Sensorial-Mathematics.html',
  24: '/decks/elementary/Week-24-Going-Out-as-Curriculum.html',
  25: '/decks/elementary/Week-25-Mathematical-Reasoning-Beyond-Computation.html',
  26: '/decks/elementary/Week-26-Algebra-in-the-Elementary-Classroom.html',
  27: '/decks/elementary/Week-27-Geometry-and-Proof.html',
  28: '/decks/elementary/Week-28-Financial-Literacy-and-Mathematics.html',
  29: '/decks/elementary/Week-29-Assessment-in-Elementary-Mathematics.html',
  30: '/decks/elementary/Week-30-When-Children-Resist-Mathematics.html',
  31: '/decks/elementary/Week-31-Solid-Geometry-and-Three-Dimensional-Thinking.html',
  32: '/decks/elementary/Week-32-The-Research-Project.html',
  33: '/decks/elementary/Week-33-Grammar-as-a-Thinking-Tool.html',
  34: '/decks/elementary/Week-34-Creative-Writing-in-Elementary.html',
  35: '/decks/elementary/Week-35-Research-Skills-and-Information-Literacy.html',
  36: '/decks/elementary/Week-36-Public-Speaking-and-Presentation.html',
  37: '/decks/elementary/Week-37-Art-History-as-Whose-History.html',
  38: '/decks/elementary/Week-38-Elements-of-Art-and-Montessori-Aesthetic-Sensibility.html',
  39: '/decks/elementary/Week-39-Music-History-and-Whose-Music-Gets-to-Be-History.html',
  40: '/decks/elementary/Week-40-Music-Theory-and-Mathematical-Thinking.html',
  41: '/decks/elementary/Week-41-The-Arts-as-Documentation-and-Resistance.html',
  42: '/decks/elementary/Week-42-Behavior-in-the-Elementary-Community.html',
  43: '/decks/elementary/Week-43-The-Community-Meeting.html',
  44: '/decks/elementary/Week-44-Conflict-Resolution-and-Restorative-Practice.html',
  45: '/decks/elementary/Week-45-Supporting-Children-With-Trauma-Histories.html',
  46: '/decks/elementary/Week-46-ADHD-Autism-and-the-Elementary-Social-World.html',
  47: '/decks/elementary/Week-47-Partnering-With-Families-at-the-Elementary-Level.html',
  48: '/decks/elementary/Week-48-Your-Elementary-Philosophy.html',
  49: '/decks/elementary/Week-49-Where-You-Came-From.html',
  50: '/decks/elementary/Week-50-The-Adolescent-Transition.html',
  51: '/decks/elementary/Week-51-What-MMR-Asks-of-You-Now.html',
}

export function getDeckUrl(track: string, weekNumber: number): string | null {
  const map = track === 'primary' ? PRIMARY_DECKS : ELEMENTARY_DECKS
  return map[weekNumber] || null
}
